export const BOOKS_LIST = 'BOOKS_LIST';
export const HOME_UPDATES = 'HOME_UPDATES';
export const CATEGORIES_LIST = 'CATEGORIES_LIST';
export const SEARCH_BOOKS = 'SEARCH_BOOKS';
export const SEARCH_CATEGORIES = 'SEARCH_CATEGORIES';

//account controls

export const SET_ACCOUNT = 'SET_ACCOUNT';
export const SET_ACCESSIBILITIES = 'SET_ACCESSIBILITIES';
export const SET_PROFILE = 'SET_PROFILE';

export const SET_RECENTS = 'SET_RECENTS';
export const SET_BOOK_INFO = 'SET_BOOK_INFO';
export const SET_BOOK_COMMENTS = 'SET_BOOK_COMMENTS';