export const BOOKS_LIST = 'BOOKS_LIST';
export const HOME_UPDATES = 'HOME_UPDATES';
export const CATEGORIES_LIST = 'CATEGORIES_LIST';
export const SEARCH_BOOKS = 'SEARCH_BOOKS';
export const SEARCH_CATEGORIES = 'SEARCH_CATEGORIES';

//account controls

export const SET_ACCOUNT = 'SET_ACCOUNT';
export const SET_ACCESSIBILITIES = 'SET_ACCESSIBILITIES';
export const SET_PROFILE = 'SET_PROFILE';

export const SET_RECENTS = 'SET_RECENTS';
export const SET_BOOK_INFO = 'SET_BOOK_INFO';
export const SET_BOOK_COMMENTS = 'SET_BOOK_COMMENTS';

export const SET_ACTIVITY_COMMENTS = 'SET_ACTIVITY_COMMENTS';
export const SET_SAVES = 'SET_SAVES';
export const SET_DOWNLOADS = 'SET_DOWNLOADS';
export const SET_BOOK_INFO_OFFLINE = 'SET_BOOK_INFO_OFFLINE'
export const SET_BOOKPAGE_RECORD = 'SET_BOOKPAGE_RECORD'

export const SET_BOOKMARKS = 'SET_BOOKMARKS';
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';

export const SET_LOADER = 'SET_LOADER';
export const SET_LOADER_CAT = 'SET_LOADER_CAT'